Fixed VirtualEnvironmentExists
BHoM/Python_Toolkit pull request #128
Opened 2023-12-04 16:05 UTC by Tom-Kingstone

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #127 

Added a check for if the executable it is trying to run actually exists before running.

### Test files

run LBT environment installer in grasshopper.

### Changelog

### Additional comments

2023-12-04 16:06 UTC, Tom-Kingstone commented
@BHoMBot check compliance
@BHoMBot check core

2023-12-04 16:54 UTC, FraserGreenroyd requested changes
Based on discussion with @jamesramsden-bh and @Tom-Kingstone , this is not the right place to add the protection - it needs adding in the `Version` method as well.

2023-12-05 08:39 UTC, Tom-Kingstone commented
@BHoMBot check compliance
@BHoMBot check required

2023-12-05 10:19 UTC, FraserGreenroyd requested changes

2023-12-05 10:19 UTC, FraserGreenroyd commented on Python_Engine/Query/Version.cs
> +            try
This method should check if the file exists before even making the `Process` object.

2023-12-05 10:19 UTC, FraserGreenroyd commented on Python_Engine/Query/VirtualEnvironment.cs
> +                versionMatches = Version(VirtualEnvironmentExecutable(envName)) == pythonVersion;
The output from `VirtualEnvironmentExecutable()` should be stored and reused as discussed given it's called twice in this method currently.

2023-12-05 11:22 UTC, FraserGreenroyd approved these changes
That looks robust now on code review @Tom-Kingstone , thanks!

2023-12-05 11:22 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-12-05 12:24 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-12-05 12:24 UTC, merged