Engine: BasePythonEnvironment boolean run
BHoM/Python_Toolkit pull request #131
Opened 2023-12-12 16:28 UTC by Tom-Kingstone

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #130 

added a boolean "run" to BasePythonEnvironment, and added `PreviousVersion` and `Input` attributes.

### Test files

place a BasePythonEnvironment component on the canvas and input a bool into run. Test that setting Run to true returns the Python environment.

### Changelog

### Additional comments

2023-12-12 16:28 UTC, Tom-Kingstone commented
@BHoMBot check core, compliance

2023-12-12 16:28 UTC, Tom-Kingstone commented
@BHoMBot check core
@BHoMBot check compliance

2023-12-12 16:30 UTC, Tom-Kingstone commented
@BHoMBot check versioning

2023-12-12 16:44 UTC, Tom-Kingstone commented
@BHoMBot check documentation-compliance

2023-12-12 16:46 UTC, FraserGreenroyd requested changes

2023-12-12 16:46 UTC, FraserGreenroyd commented on Python_Engine/Compute/BasePythonEnvironment.cs
> +            bool run = false,
This should be the last input rather than the first

2023-12-12 16:46 UTC, FraserGreenroyd commented on Python_Engine/Compute/BasePythonEnvironment.cs
> +        [PreviousVersion("BH.Engine.Python.Compute.BasePythonEnvironment(System.Boolean)")]
```suggestion
        [PreviousVersion("7.0", "BH.Engine.Python.Compute.BasePythonEnvironment(System.Boolean)")]
```

2023-12-12 16:47 UTC, Tom-Kingstone commented
@BHoMBot check compliance
@BHoMBot check versioning

2023-12-13 08:23 UTC, Tom-Kingstone commented
@BHoMBot check core

2023-12-13 08:24 UTC, Tom-Kingstone commented
@BHoMBot check versioning

2023-12-13 08:43 UTC, Tom-Kingstone commented
@BHoMBot check required

2023-12-13 08:46 UTC, FraserGreenroyd approved these changes
Providing all checks pass then this is good from code inspection, cheers @Tom-Kingstone

2023-12-13 09:10 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 19589955334

2023-12-13 09:10 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-12-13 09:13 UTC, merged