Ensure availability of base Python environment
BHoM/Python_Toolkit pull request #74
Opened 2022-02-11 14:51 UTC by tg359

### Issues addressed by this PR

Closes #73 
Closes #72 

Enables creation of requirements.txt file, rather than relying on one for environment creation, and moves definition of the environment into a toolkit-specific *_Toolkit.json for placement in %ProgramData%\BHoM\Settings\Python. Checks to see whether the base Python environment is available for future dependence on core decorators referenced by downstream methods.

### Test files

[BHoM_Test.zip](https://github.com/BHoM/Python_Toolkit/files/8049461/BHoM_Test.zip)

### Changelog

### Additional comments

2022-02-11 15:28 UTC, tg359 commented
@BHoMBot check required

2022-02-16 10:05 UTC, FraserGreenroyd requested changes

2022-02-16 10:05 UTC, FraserGreenroyd commented on Python_Engine/Compute/InstallPythonEnvironment.cs
> +        public static PythonEnvironment InstallPythonEnvironment(bool run = false, bool force = false, string configJSON = @"C:\ProgramData\BHoM\Settings\Python\Python_Toolkit.json")
```suggestion
        [PreviousVersion("5.1", "BH.Engine.Python.Compute.InstallPythonEnvironment(System.Boolean, System.Boolean)")]
        public static PythonEnvironment InstallPythonEnvironment(bool run = false, bool force = false, string configJSON = @"C:\ProgramData\BHoM\Settings\Python\Python_Toolkit.json")
```

2022-02-16 10:05 UTC, FraserGreenroyd commented on Python_Engine/Compute/InstallPythonEnvironment.cs
> +        public static PythonEnvironment InstallPythonEnvironment(this PythonEnvironment pythonEnvironment, bool force = false, bool run = false)
```suggestion
        [PreviousVersion("5.1", "BH.Engine.Python.Compute.InstallToolkitPythonEnvironment(BH.oM.Python.PythonEnvironment, System.Boolean, System.Boolean)")]
        public static PythonEnvironment InstallPythonEnvironment(this PythonEnvironment pythonEnvironment, bool force = false, bool run = false)
```

2022-02-16 10:05 UTC, FraserGreenroyd commented on Python_Engine/Create/PythonEnvironment.cs
> +        [Input("config", "The path to the environment.json config file.")]
```suggestion
        [Input("configJSON", "The path to the environment.json config file.")]
```

2022-02-16 10:12 UTC, FraserGreenroyd commented
@BHoMBot check core

2022-02-16 10:17 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-02-16 10:20 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 5214476667

2022-02-16 10:21 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-02-16 10:24 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer

2022-02-21 09:12 UTC, FraserGreenroyd commented
@BHoMBot check core

2022-02-21 09:16 UTC, FraserGreenroyd commented
@BHoMBot check installer

2022-02-21 09:47 UTC, FraserGreenroyd commented
@BHoMBot check installer

2022-02-21 09:57 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check versioning

2022-02-21 10:31 UTC, FraserGreenroyd commented
@BHoMBot check null-handling
@BHoMBot check serialisation

2022-02-21 11:49 UTC, FraserGreenroyd approved these changes
Have run through with @tg359 and this is good to go to alpha for further testing.

2022-02-21 12:32 UTC, merged