BHoM managed Python virtualenvs
BHoM/Python_Toolkit pull request #85
Opened 2022-08-15 09:49 UTC by tg359

### Issues addressed by this PR

Closes #83 
Closes #81 
Closes #79 
Closes #62 
Closes #46 

Handling of Python environments via BHoM rationalised around a base "full" environment, and virtualenvs for any toolkit/project-specific environment that can be pre-defined with custom codebases via a referenced local-package added upon installation.

### Test files

[83.zip](https://github.com/BHoM/Python_Toolkit/files/9336409/83.zip)

### Changelog

### Additional comments

2022-08-15 09:59 UTC, tg359 commented
@BHoMBot check required

2022-08-18 15:23 UTC, alelom commented on Python_Engine/Compute/DownloadPython.cs
> +        [Description("Download a the target version of Python.")]
```suggestion
        [Description("Download a target version of Python.")]
```

2022-08-18 15:27 UTC, alelom commented on Python_Engine/Compute/InstallBasePythonEnvironment.cs
> +            {
```suggestion
            if (!run)
            return
```

2022-08-18 15:29 UTC, alelom commented on Python_Engine/Compute/InstallBasePythonEnvironment.cs
> +            {
Please remove indented block
```suggestion
            if (!run)
                return;
```

2022-08-18 15:32 UTC, alelom commented on Python_Engine/Compute/InstallReferencedVirtualenv.cs
> +            {
Please remove indented block. Perhaps consider adding a warning to alert user to toggle `run` to `true`.
```suggestion
            if (!run)
            {
               BH.Engine.Base.Compute.RecordWarning($"Please toggle `{nameof(run)}` to true.");
               return;
            }
```

2022-08-18 15:33 UTC, alelom commented on Python_Engine/Compute/InstallVirtualenv.cs
> +            {
Please remove indented block. Perhaps consider adding a warning to alert user to toggle `run` to `true`.
```suggestion
            if (!run)
            {
               BH.Engine.Base.Compute.RecordWarning($"Please toggle `{nameof(run)}` to true.");
               return null;
            }
```

2022-08-18 15:36 UTC, alelom commented on Python_Engine/Compute/RemoveVirtualenv.cs
> +            {
Please remove indented block. Perhaps consider adding a warning to alert user to toggle `run` to `true`.
```suggestion
            if (!run)
            {
               BH.Engine.Base.Compute.RecordWarning($"Please toggle `{nameof(run)}` to true.");
               return null;
            }
```

2022-08-18 15:57 UTC, alelom commented on Python_Engine/Compute/Run.cs
> +            process.WaitForExit();
What happens if the process hangs indefinitely without exiting? I think this way the process may deadlock Grasshopper's UI. Shouldn't we consider something like:
```suggestion
            int timeoutMinutes = 5; // should be an input parameter to the method
            int millisecondsToWait = 5 * 60 * 1000;
            process.WaitForExit(millisecondsToWait);
            if (!myProcess.HasExited)
		process.Kill();
```

2022-08-18 16:00 UTC, alelom commented on Python_Engine/Compute/Run.cs
> +            process.WaitForExit();
What happens if the process hangs indefinitely without exiting? I think this way the process may deadlock Grasshopper's UI. Shouldn't we consider something like:
```suggestion
            int timeoutMinutes = 5; // should be an input parameter to the method
            int millisecondsToWait = 5 * 60 * 1000;
            process.WaitForExit(millisecondsToWait);
            if (!myProcess.HasExited)
		process.Kill();
```

2022-08-18 16:01 UTC, alelom requested changes
Looks great! I have not yet tested it, just had a look at the code. Will test it soon. Could you have a look at my suggestions?

2022-08-25 13:03 UTC, alelom submitted a review, later dismissed
Thanks for the changes @tg359 , code now looks good to me.
The test file run as in the following image.  
It's not explicit whether the second component should fail intentionally, but it looks like so (incorrect python command requested).
Another note is on the runtime: on my machine, the `InstallBasePythonEnvironment` method took over 3 minutes (see screenshot), but I guess that is unavoidable. The other components took an average of 2 secs.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/6352844/186671518-08c36d14-25a3-4746-aec3-f6d692b76b62.png">

Approving based on the above.

2022-08-26 09:02 UTC, tg359 commented
@BHoMBot check required

2022-09-09 08:25 UTC, tg359 commented
@BHoMBot check compliance

2022-09-09 08:44 UTC, tg359 commented
@BHoMBot check compliance

2022-09-09 09:40 UTC, tg359 commented
@BHoMBot check versioning

2022-09-09 09:41 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2022-09-09 10:09 UTC, FraserGreenroyd commented
@BHoMBot check core

2022-09-09 13:02 UTC, tg359 commented
@BHoMBot check versioning

2022-09-09 14:02 UTC, tg359 commented
@BHoMBot check versioning

2022-09-09 14:55 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-09-09 15:22 UTC, FraserGreenroyd commented
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check serialisation

2022-09-09 16:10 UTC, FraserGreenroyd approved these changes
Approving based on @alelom review as commits since then have been versioning and compliance.

2022-09-09 16:23 UTC, merged